name: Run simple tests to installer

on:
  push:
    branches:
      - '*'


jobs:
  run-tests:
    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest ]
        recipes: [ install_stow, install_tmux, install_neovim ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - run: make ${{ matrix.recipes }}
